### ISSUE TITLE
Some files were missed

### ISSUE THREAD

**Issue by GuohuaZhu** [kbolton-lab/Bolton_OCCC#1]
Dear professors，could you help me with the follow files. I can't find it according your description.
Thanks for your kindly help.
```
source('utils/fisher_toolbox.R')
source('utils/plot_comutation_ggplot.R')
source("utils/get_protein_info.R")
source("utils/my_lollipop.R")
```

**Comment by IrenaeusChan** [comment]
Hello, we have uploaded the necessary required utils for this project. Let us know if you have any issues and if not I will close this issue in a week.

Thanks!
