### ISSUE TITLE
RNA-seq data

### ISSUE THREAD

**Issue by zhangguy** [kbolton-lab/Bolton_OCCC#2]
Hi, 

Could you provide more details for the RNA-seq data file [CCOC.RNAseq.normalized.rds](https://github.com/kbolton-lab/Bolton_OCCC/blob/master/processing/CCOC.RNAseq.normalized.rds)?
Is it normalized counts, FPKM or TPM? Was it log2 or log10 transformed?

Thanks!

**Comment by IrenaeusChan** [comment]
Hello,

According to the paper, DESeq2 was used to perform the differential expression analysis. DESeq2 uses the median of ratios method for its [normalization methodology](https://hbctraining.github.io/DGE_workshop/lessons/02_DGE_count_normalization.html).

**Comment by zhangguy** [comment]
> Hello,
> 
> According to the paper, DESeq2 was used to perform the differential expression analysis. DESeq2 uses the median of ratios method for its [normalization methodology](https://hbctraining.github.io/DGE_workshop/lessons/02_DGE_count_normalization.html).

Thanks for your fast response. Is it possible to share the raw counts? Thanks

**Comment by IrenaeusChan** [comment]
Hello, unfortunately the original owner of the RNAseq data is unable to locate the unnormalized data so we are unable to provide the raw counts.

**Comment by zhangguy** [comment]
Thanks for your reply. Not asking to share but hope the fastq files are
still there. This is a invaluable dataset from a sizable cohort of a rare
cancer.

**Comment by IrenaeusChan** [comment]
Hello, could you email me at chani@wustl.edu

I can provide the RNA sequencing BAMs for your research
